const userMessage = [
  /*1*/  ["hi", "hey", "hello", "hii"],
  /*2*/  ["sure", "yes", "no"],
  /*3*/  ["are you genious", "are you nerd", "are you intelligent"],
  /*4*/  ["i hate you", "i dont like you"],
  /*5*/  ["how are you", "how is life", "how are things", "how are you doing"],
  /*6*/  ["how is corona", "how is covid 19", "how is covid19 situation"],
  /*7*/  ["what are you doing", "what is going on", "what is up"],
  /*8*/  ["how old are you"],
  /*9*/  ["who are you", "are you human", "are you bot", "are you human or bot"],
  /*10*/ ["who created you", "who made you", "who is your creator"],
  /*11*/ [
          "your name please",
          "your name",
          "may i know your name",
          "what is your name",
          "what call yourself"
        ],
  /*12*/ ["i love you"],
  /*13*/ ["happy", "good", "fun", "wonderful", "fantastic", "cool", "very good"],
  /*14*/ ["bad", "bored", "tired"],
  /*15*/ ["help me", "tell me story", "tell me joke"],
  /*16*/ ["ah", "ok", "okay", "nice", "welcome"],
  /*17*/ ["thanks", "thank you"],
  /*18*/ ["what should i eat today"],
  /*19*/ ["bro"],
  /*20*/ ["what", "why", "how", "where", "when"],
  /*21*/ ["corona", "covid19", "coronavirus"],
  /*22*/ ["you are funny"],
  /*23*/ ["i dont know"],
  /*24*/ ["boring"],
  /*25*/ ["im tired", "i am tried"],
  /*26*/ [
          "neighbour dog bite me what can i do", 
          "neighbour dog bite me. what can i do"
        ],
  /*27*/ [
          "neighbour cat bite me what can i do", 
          "neighbour cat bite me. what can i do"
        ],
  /*28*/ [
          "someone is repeatedly calling me",
          "someone is repeatedly harassing me",
          "my friend is repeatedly calling me"
        ],
  /*29*/ ["what is ipc", "ipc"],
  /*30*/ ["bns", "what is bns"],
  /*31*/ ["rape"],
  /*32*/ ["kidnapping", "children kindnapping"],
  /*33*/ ["sexual harassment"],
  /*34*/ ["sexual intercourse by husband upon his wife during separation", "when husband seprates but they push me to sexual "],
  /*35*/ ["gangrape", "gang rape"],
  /*36*/ ["gang rape on a woman under eighteen years of age", "gangrape under eighteen", "gangrape under eighteen child"],
  /*37*/ ["dowry death"],
  /*38*/ ["murder"],
  /*39*/ ["gang murder", "gangmurder"],
  /*40*/ ["murder by life convict"],
  /*41*/ ["kidnapping"],
  /*42*/ ["kidnapping a child for purposes of begging."],
  /*43*/ ["maiming a child for purposes of begging"],
  /*44*/ ["voluntarily causing hurt", "voluntary"],
  /*45*/ ["right to education", "education free or not", "education law"],
  /*46*/ ["living wage", "living wage workers"],
  /*47*/ ["duration of houses of parliament", "what is the duration of parliament", "parliament hours"],
  /*48*/ ["qualification for membership of parliament", "qualification of parliament members", "any qulaification for member of parliament"],
  /*49*/ ["salaries and allowances of members", "salaries of members in parliament"],
  /*50*/ ["annual financial statement"],
  /*51*/ ["appropriation Bills", "supply bill", "what is supply bill", "spending bill", "what is spending bill"],
  /*52*/ ["supplementary additional or excess grants", "supplementary laws" , "what is supplementary", "additional grants", "what is additional grants", "excess grants", "what is excess grants"],
  /*53*/ ["votes on account, votes of credit and exceptional grants", "votes on account", "votes of credit", "votes of exceptional grants", "what is votes of exceptional grants", "what is votes of credit"],
  /*54*/ ["which language is used in parliment", "tamil language is used in parliment", "common language is used in parliment", "commonly used language in parliment"],
  /*55*/ ["governors of states", "who is governor of states"],
  /*56*/ ["executive power of state"],
  /*57*/ ["appointment of governor", "how appointment governer", "governer appointment"],
  /*58*/ ["term of office of governor", "how many years governer can rule", "expiration of governer"],
  /*59*/ ["qualifications for appointment as governor"],
  /*60*/ ["conditions of governor office", "list out the conditions of governer", "governer conditions"],
  /*61*/ ["gram sabha"],
  /*62*/ ["constitution of panchayats", "what are the constitution in panchayats", "what are the constitution in panchayat"],
  /*63*/ ["composition of panchayats"],
  /*64*/ ["duration of panchayats"],
  /*65*/ ["disqualifications for membership"],
  /*66*/ ["warrant directed to police officer"],
  /*67*/ ["notification of substance of warrant"],
  /*68*/ ["where warrant may be executed"],
  /*69*/ ["When search-warrant may be issued"],
  /*70*/ ["order to give security"],
];


const botReply = [
  /*1*/ ["Hello!", "Hi!", "Hey!", "Hi there!"],
  /*2*/ ["Okay"],
  /*3*/ ["Yes I am! "],
  /*4*/ ["I'm sorry about that. But I like you dude."],
  /*5*/ [
          "Fine... how are you?",
          "Pretty well, how are you?",
          "Fantastic, how are you?"
        ],
  /*6*/ ["Getting better. There?", "Somewhat okay!", "Yeah fine. Better stay home!"],
  /*7*/ [
          "Nothing much",
          "About to go to sleep",
          "Can you guess?",
          "I don't know actually"
        ],
  /*8*/  ["I am always young."],
  /*9*/  ["I am just a bot", "I am a bot. What are you?"],
  /*10*/ ["Sabitha Kuppusamy"],
  /*11*/ ["I am Legal law chat assistant"],
  /*12*/ ["I love you too", "Me too"],
  /*13*/ ["Have you ever felt bad?", "Glad to hear it"],
  /*14*/ ["Why?", "Why? You shouldn't!", "Try watching TV", "Chat with me."],
  /*15*/ ["What about?", "Once upon a time..."],
  /*16*/ ["Tell me a story", "Tell me a joke", "Tell me about yourself"],
  /*17*/ ["You're welcome"],
  /*18*/ ["Briyani", "Burger", "Sushi", "Pizza"],
  /*19*/ ["Dude!"],
  /*20*/ ["Yes?"],
  /*21*/ ["Please stay home"],
  /*22*/ ["Glad to hear it"],
  /*23*/ ["Say something interesting"],
  /*24*/ ["Sorry for that. Let's chat!"],
  /*25*/ ["Take some rest, Dude!"],
  /*26*/ ["which has the exact same wordings as Section 291 of the BNS, imposed a fine of upto Rs 1,000, along with imprisonment upto six months."],
  /*27*/ ["There is no any specific law for the cat bitten, but Under the BNS pet animal attacks a human, the  can be fined upto 5000 INR along with imprisonment upto six months."], 

  /*28*/ ["According to the section 264 in criminal code, contacting someone regularly either to harassing or threaten another will end up him being for 10 years."],
  /*29*/ ["An indian penal code. It was offical criminal code in india"],
  /*30*/ ["An Bharatiya Nyaya Sanhita, is the criminal code of india. It will replace the indian penal code"],
  /*31*/ ["In consensual rape cases the existing age limit has been raised from 15 years to 18 years and it will be differ from age based."],
  /*32*/ ["Makes the kidnapping of all children below 18 years an offence. It emphasized the broader protection extended to all children."],
  /*33*/ ["This offense of sexual harassment committed by a man, which includes physical contact with unwelcome and explicit sexual overtures, demanding sexual favors, showing pornography against the woman's will, and making sexually colored remarks. The punishment for committing such offenses varies, with imprisonment for up to three years, fine, or both."],
  /*34*/ ["The Sexual intercourse by husband upon his wife during separation. Imprisonment for not less than 2 years but which may extend to 7 years and fine. Cognizable when only on the complaint of the victim. This is Bailable case."],
  /*35*/ ["Rigorous imprisonment for not less than 20 years but which may extend to imprisonment for life which shall mean imprisonment for the remainder of that person’s natural life and fine. this is non bailable case"],
  /*36*/ ["Imprisonment for life which shall mean imprisonment for the remainder of that person’s natural life and with fine or with death. it is non bailable case"],
  /*37*/ ["In this case, They can Imprisonment for not less than 7 years but which may extend to imprisonment for life."],
  /*38*/ ["Death or imprisonment for life and fine. This is non bailable based on cases."],
  /*39*/ ["Death or imprisonment for life and fine. This is non bailable based on cases."],
  /*40*/ ["Death or imprisonment for life, which shall mean the remainder of that person’s natural life. This is non bailable case."],
  /*41*/ ["Imprisonment for 7 years and fine. This is bailable"],
  /*42*/ ["Rigorous imprisonment may not be less than 10 years but which may extend to imprisonment for life, and fine. This is non bailable case"],
  /*43*/ ["Imprisonment not be less than 20 years which may extend to remainder of that person’s natural life, and fine. This is non bailable case"],
  /*44*/ ["Whoever does any act with the intention of thereby causing hurt to any person, or with the knowledge that he is likely thereby to cause hurt to any person, and does thereby cause hurt to any person, is said “voluntarily to cause hurt“."],
  /*45*/ ["The State shall provide free and compulsory education to all children of the age of six to fourteen years in such manner as the State may, by law, determine."],
  /*46*/ ["The State shall endeavour to secure, by suitable legislation or economic organisation or in any other way, to all workers, agricultural, industrial or otherwise, work, a living wage, conditions of work ensuring a decent standard of life and full enjoyment of leisure and social and cultural opportunities and, in particular, the State shall endeavour to promote cottage industries on an individual or co-operative basis in rural areas."],
  /*47*/ ["The Council of States shall not be subject to dissolution, but as nearly as possible one-third of the members thereof shall retire as soon as may be on the expiration of every second year in accordance with the provisions made in that behalf by Parliament by law. And it also be subject to The House of the People, unless sooner dissolved, shall continue for five years from the date appointed for its first meeting a.nd no longer and the expiration of the said period of five years shall operate as a dissolution of the House."],
  /*48*/ ["A person shall not be qualified to be chosen to fill a seat in Parliament unless he is a citizen of India, and makes and subscribes before some person authorised in that behalf by the Election Commission an oath or affirmation according to the form set out for the purpose in the Third Schedule is, in the case of a seat in the Council of States, not less than thirty years of age and, in the case of a seat in the House of the People, not less than twenty-five years of age; and possesses such other qualifications as may be prescribed in that behalf by or under any law made by Parliament."],
  /*49*/ ["Members of either House of Parliament shall be entitled to receive such salaries and allowances as may from time to time be determined by Parliament by law and, until provision in that respect is so made, allowances at such rates and upon such conditions as were immediately before the commencement of this Constitution applicable in the case of members of the Constituent Assembly of the Dominion of India."],
  /*50*/ ["The President shall in respect of every financial year cause to be laid before both the Houses of Parliament a statement of the estimated receipts and expenditure of the Government of India for that year, in this Part referred to as the “annual financial statement."],
  /*51*/ ["As soon as may be after the grants under article 113 have been made by the House of the People, there shall be introduced a Bill to provide for the appropriation out of the Consolidated Fund of India of all moneys required to meet the grants so made by the House of the People."],
  /*52*/ ["The President shall - if the amount authorised by any law made in accordance with the provisions of article 114 to be expended for a particular service for the current financial year is found to be insufficient for the purposes of that year or when a need has arisen during the current financial year for supplementary or additional expenditure upon some new service not contemplated in the annual financial statement for that year."],
  /*53*/ ["Not with standing anything in the foregoing provisions of this Chapter, the House of the People shall have power to make any grant in advance in respect of the estimated expenditure for a part of any financial year pending the completion of the procedure prescribed in article 113 for the voting of such grant and the passing of the law in accordance with the provisions of article 114 in relation to that expenditure."],
  /*54*/ ["Not with standing anything in Part XVII, but subject to the provisions of article 348, business in Parliament shall be transacted in Hindi or in English. Provided that the Chairman of the Council of States or Speaker of the House of the People, or person acting as such, as the case may be, may permit any member who cannot adequately express himself in Hindi or in English to address the House in his mother-tongue."],
  /*55*/ ["There shall be a Governor for each State, and Provided that nothing in this article shall prevent the appointment of the same person as Governor for two or more States"],
  /*56*/ ["The executive power of the State shall be vested in the Governor and shall be exercised by him either directly or through officers subordinate to him in accordance with this Constitution."],
  /*57*/ ["The Governor of a State shall be appointed by the President by warrant under his hand and seal."],
  /*58*/ ["The Governor shall hold office during the pleasure of the President. The Governor may, by writing under his hand addressed to the President, resign his office. Subject to the foregoing provisions of this article, a Governor shall hold office for a term of five years from the date on which he enters upon his office."],
  /*59*/ ["No person shall be eligible for appointment as Governor unless he is a citizen of India and has completed the age of thirty-five years."],
  /*60*/ ["The Governor shall not be a member of either House of Parliament or of a House of the Legislature of any State specified in the First Schedule, and if a member of either House of Parliament or of a House of the Legislature of any such State be appointed Governor, he shall be deemed to have vacated his seat in that House on the date on which he enters upon his office as Governor."],
  /*61*/ ["A Gram Sabha may exercise such powers and perform such functions at the village level as the Legislature of a State may, by law, provide."],
  /*62*/ ["There shall be constituted in every State, Panchayats at the village, intermediate and district levels in accordance with the provisions of this Part, Panchayats at the intermediate level may not be constituted in a State having a population not exceeding twenty lakhs."],
  /*63*/ ["Subject to the provisions of this Part, the Legislature of a State may, by law, make provisions with respect to the composition of Panchayats, Provided that the ratio between the population of the territorial area of a Panchayat at any level and the number of seats in such Panchayat to be filled by election shall, so far as practicable, be the same throughout the State."],
  /*64*/ ["Every Panchayat, unless sooner dissolved under any law for the time being in force, shall continue for five years from the date appointed for its first meeting and no longer. No amendment of any law for the time being in force shall have the effect of causing dissolution of a Panchayat at any level, which is functioning immediately before such amendment, till the expiration of its duration specified in clause."],
  /*65*/ ["A person shall be disqualified for being chosen as, and for being, a member of a Panchayat, if he is so disqualified by or under any law for the time being in force for the purposes of elections to the Legislature of the State concerned: Provided that no person shall be disqualified on the ground that he is less than twenty-five years of age, if he has attained the age of twenty-one years."],
  /*66*/ ["A warrant directed to any police officer may also be executed by any other police officer whose name is endorsed upon the warrant by the officer to whom it is directed or endorsed."],
  /*67*/ ["The police officer or other person executing a warrant of arrest shall notify the substance thereof to the person to be arrested, and, if so required, shall show him the warrant."],
  /*68*/ ["A warrant of arrest may be executed at any place in India."],
  /*69*/ ["The court Where any Court has reason to believe that a person to whom a summons or order under section 91 or a requisition under Sub-Section (1) of section 92 has been, or might be, addressed, will not or would not produce the document or thing as required by such summons or requisition."],
  /*70*/ ["If, upon such inquiry, it is proved that it is necessary for keeping the peace or maintaining good behaviour, as the case may be, that the person in respect of whom the inquiry is made should execute a bond, with or without sureties, the Magistrate shall make an order accordingly,person shall be ordered to give security of a nature different from, or of an amount larger than, or for a period longer than, that specified in the order made under section 111."],
];

const alternative = [
  "Same here, dude.",
  "That's cool! Go on...",
  "Dude...",
  "Ask something else...",
  "Hey, I'm listening..."
];
